# This is an example configuration file
# used for development and testing purposes.
#
# For the effective config used in production for
# docs.giantswarm.io, see
# https://github.com/giantswarm/docs/blob/main/scripts/update-crd-reference/config.yaml

# template_path: templates/crd.template

output_path: out

# List of repositories containing CRDs.
# Sequence is important here if several repos provide the same CRD (based on the full name).
# In this case, the first repo "wins". Subsequent repos adding the same CRD will result in a
# warning.
source_repositories:
  - url: https://github.com/kubeshop/testkube
    organization: kubeshop
    short_name: testkube
    commit_reference: v1.11.18
    crd_paths:
      - config/crd
    cr_paths:
      - docs/cr
  
